on:
  pull_request:
    types:
      - opened
      - closed
      - labeled

name: Release workflows

jobs:
  release_workflow:
    uses: hoangvvo/gitflow-workflow-action-test/.github/workflows/test.yaml@main
