on:
  workflow_call:
    inputs:
      test:
        required: false
        type: string
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/github-script@v6
        with:
          script: console.log(context)
